// ref: https://mui.com/material-ui/integrations/nextjs/
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./styles.scss";
import { Container } from '@mui/material';
import  NavBar from "../component/Navbar/NavBar";
import  ThemeContextProvider from "@/context/ThemeContext"
import CssBaseline from '@mui/material/CssBaseline';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeContextProvider>
            <CssBaseline /> 
              <NavBar/>
              <Container maxWidth="lg">
                {children}
              </Container>
          </ThemeContextProvider>         
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
