// ref: https://mui.com/material-ui/integrations/nextjs/
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./styles.scss";
import { ThemeProvider } from '@mui/material/styles';
import theme from "./theme";
import { Container } from '@mui/material';
import { NarBar } from "@/component/NarBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <NarBar/>
              <Container maxWidth="lg">
                {children}
              </Container>
            </ThemeProvider>         
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
