version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Make sure to specify your Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ROOT_PATH=http://backend:80/api  # Pointing to backend
    depends_on:
      backend:
        condition: service_healthy  # Wait for backend to pass healthcheck
    networks:
      - app-network

networks:
  app-network:
    driver: bridge